---
- hosts: all
  gather_facts: True
  sudo: True
  vars:
    mariadb_bind_address: "0.0.0.0"

  roles:
    - marklee77.docker
    - marklee77.mariadb
    - marklee77.rabbitmq-server
    - marklee77.keystone

- hosts: all
  gather_facts: True
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - python-mysqldb
        - python-keystoneclient
        - python-novaclient
